# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero_contrat', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Numéro de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('loyer_mensuel', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Loyer mensuel (FCFA)')),
                ('caution_versee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution versée (FCFA)')),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINEE', 'Terminée'), ('RESILIEE', 'Résiliée'), ('SUSPENDUE', 'Suspendue')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('contrat_pdf', models.FileField(blank=True, null=True, upload_to='rentals/contrats/', verbose_name='Contrat PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['-date_debut'],
            },
        ),
    ]
