# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('date_debut_souhaitee', models.DateField(verbose_name='Date de début souhaitée')),
                ('duree_mois', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('reponse_admin', models.TextField(blank=True, verbose_name='Réponse admin')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.maison', verbose_name='Maison')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
