# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_facture', models.CharField(choices=[('LOYER', 'Loyer'), ('SODECI', 'SODECI (Eau)'), ('CIE', 'CIE (Électricité)'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('index_ancien', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Index ancien')),
                ('index_nouveau', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Index nouveau')),
                ('consommation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Consommation (unités)')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Part de consommation du locataire', max_digits=5, null=True, verbose_name='Pourcentage (%)')),
                ('mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-annee', '-mois', '-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='FactureCollective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_facture', models.CharField(choices=[('SODECI', 'SODECI (Eau)'), ('CIE', 'CIE (Électricité)')], max_length=20, verbose_name='Type')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total (FCFA)')),
                ('mois', models.PositiveIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('consommation_totale', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Consommation totale')),
                ('repartie', models.BooleanField(default=False, verbose_name='Répartie')),
                ('date_repartition', models.DateTimeField(blank=True, null=True, verbose_name='Date de répartition')),
            ],
            options={
                'verbose_name': 'Facture collective',
                'verbose_name_plural': 'Factures collectives',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='IndexCompteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('type_compteur', models.CharField(choices=[('SODECI', 'SODECI (Eau)'), ('CIE', 'CIE (Électricité)')], max_length=20, verbose_name='Type')),
                ('index_valeur', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Valeur de l'index")),
                ('mois', models.PositiveIntegerField(verbose_name='Mois')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('date_releve', models.DateField(auto_now_add=True, verbose_name='Date du relevé')),
                ('photo_compteur', models.ImageField(blank=True, null=True, upload_to='billing/compteurs/', verbose_name='Photo du compteur')),
            ],
            options={
                'verbose_name': 'Index compteur',
                'verbose_name_plural': 'Index compteurs',
                'ordering': ['-annee', '-mois'],
            },
        ),
    ]
