# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
        migrations.AlterUniqueTogether(
            name='facturecollective',
            unique_together={('type_facture', 'mois', 'annee')},
        ),
        migrations.AddField(
            model_name='indexcompteur',
            name='locataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_compteurs', to=settings.AUTH_USER_MODEL, verbose_name='Locataire'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['locataire', 'statut'], name='billing_fac_locatai_57e18e_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['mois', 'annee'], name='billing_fac_mois_a4336e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('locataire', 'type_facture', 'mois', 'annee')},
        ),
        migrations.AlterUniqueTogether(
            name='indexcompteur',
            unique_together={('locataire', 'type_compteur', 'mois', 'annee')},
        ),
    ]
