# Generated by Django 6.0.3 on 2026-03-11 19:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('numero', models.CharField(help_text='Numéro inscrit sur le compteur physique', max_length=50, unique=True, verbose_name='Numéro du compteur')),
                ('type_compteur', models.CharField(choices=[('SODECI', 'SODECI (Eau)'), ('CIE', 'CIE (Électricité)')], max_length=20, verbose_name='Type')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('dernier_index', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Dernier index relevé')),
                ('date_dernier_releve', models.DateField(blank=True, null=True, verbose_name='Date du dernier relevé')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='billing/compteurs/', verbose_name='Photo du compteur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('locataire_actuel', models.ForeignKey(blank=True, help_text='Locataire qui utilise actuellement ce compteur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compteurs_utilises', to=settings.AUTH_USER_MODEL, verbose_name='Locataire actuel')),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compteurs', to='properties.maison', verbose_name='Maison/Appartement')),
            ],
            options={
                'verbose_name': 'Compteur',
                'verbose_name_plural': 'Compteurs',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='indexcompteur',
            name='compteur',
            field=models.ForeignKey(blank=True, help_text='Compteur physique concerné', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='billing.compteur', verbose_name='Compteur'),
        ),
    ]
