# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('type_logement', models.CharField(choices=[('STUDIO', 'Studio'), ('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex'), ('APPARTEMENT', 'Appartement')], default='F2', max_length=20, verbose_name='Type de logement')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix mensuel (FCFA)')),
                ('caution', models.DecimalField(decimal_places=2, help_text='Généralement équivalent à 1 ou 2 mois de loyer', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Caution (FCFA)')),
                ('charges_incluses', models.BooleanField(default=False, help_text='Si True, SODECI/CIE inclus dans le prix', verbose_name='Charges incluses')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(default='Abidjan', max_length=100, verbose_name='Ville')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('nombre_chambres', models.PositiveIntegerField(default=1, verbose_name='Nombre de chambres')),
                ('nombre_salles_bain', models.PositiveIntegerField(default=1, verbose_name='Nombre de salles de bain')),
                ('nombre_toilettes', models.PositiveIntegerField(default=1, verbose_name='Nombre de toilettes')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Superficie (m²)')),
                ('equipements', models.JSONField(blank=True, default=list, help_text="Liste des équipements: ['climatisation', 'cuisine équipée', ...]", verbose_name='Équipements')),
                ('commodites', models.JSONField(blank=True, default=list, help_text="['école', 'supermarché', 'transport', ...]", verbose_name='Commodités')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LOUEE', 'Louée'), ('EN_MAINTENANCE', 'En maintenance'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('meublee', models.BooleanField(default=False, verbose_name='Meublée')),
                ('animaux_acceptes', models.BooleanField(default=False, verbose_name='Animaux acceptés')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['statut', 'prix'], name='properties__statut_33fb73_idx'), models.Index(fields=['ville', 'commune'], name='properties__ville_3716ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageMaison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.maison', verbose_name='Maison')),
            ],
            options={
                'verbose_name': 'Image de maison',
                'verbose_name_plural': 'Images de maisons',
                'ordering': ['-est_principale', 'ordre'],
            },
        ),
    ]
