# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('email', models.EmailField(error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=254, unique=True, verbose_name='Adresse email')),
                ('telephone', models.CharField(error_messages={'unique': 'Ce numéro de téléphone est déjà utilisé.'}, max_length=20, unique=True, verbose_name='Téléphone')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=100, verbose_name='Prénoms')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('LOCATAIRE', 'Locataire')], default='LOCATAIRE', max_length=20, verbose_name='Rôle')),
                ('statut', models.CharField(choices=[('A_JOUR', 'À jour'), ('EN_RETARD', 'En retard'), ('SUSPENDU', 'Suspendu')], default='A_JOUR', max_length=20, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Photo de profil')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membre du staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email vérifié')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('employeur', models.CharField(blank=True, max_length=200, verbose_name='Employeur')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, verbose_name="Nom du contact d'urgence")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone du contact d'urgence")),
                ('contact_urgence_relation', models.CharField(blank=True, max_length=100, verbose_name='Relation')),
                ('notifications_email', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('notifications_sms', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('piece_identite', models.FileField(blank=True, null=True, upload_to='users/documents/', verbose_name="Pièce d'identité")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
