# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.CharField(choices=[('MAINTENANCE', 'Maintenance'), ('REPARATION', 'Réparation'), ('AMENAGEMENT', 'Aménagement'), ('TAXE', 'Taxe'), ('ASSURANCE', 'Assurance'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='expenses/justificatifs/', verbose_name='Justificatif')),
                ('maison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='properties.maison', verbose_name='Maison')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
    ]
